version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'npm'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    groups:
      dev-deps:
        patterns:
          - '@sveltejs/*'
          - '@fontsource/*'
          - 'eslint*'
          - 'prettier*'
          - 'svelte*'
          - 'typescript*'
          - 'vite*'
          - 'vitest*'
          - 'wrangler'
      prod-deps:
        patterns:
          - 'chota'
          - 'devicon'
